### ISSUE TITLE
Incorrect pinout diagram label for P2_28 gpio

### ISSUE THREAD

**Issue by derekmulcahy** [beagleboard/pocketbeagle#11]
The pinout image for the pocket beagle has the wrong GPIO pin number for P2_28. It is labelled as 124 but the pocket beagle schematic links it to MCASP0_AXR1. This pin is described on P36 of the data sheet as being gpio3_20. The math (3x32+20) would indicate that this is really pin 116. 

The device tree has the correct mapping for P2_28.

`gpio = <0x160 0x14 0x0>;`

The 0x14 is an offset of 20. This mapping works fine with config-pin to toggle the P2_28 gpio.

**Comment by derekmulcahy** [comment]
I also think the label for P1_33 should be GPIO 111 and not 110.

**Comment by derekmulcahy** [comment]
Updated image attached with P1_33 = GPIO 111, P2_24 = GPIO 44, P2_28 = GPIO 116

<img width="2094" alt="pocketbeagle pinout" src="https://user-images.githubusercontent.com/879075/32295675-6261887c-bf20-11e7-93d2-d1cdfa6e723e.png">

**Comment by jadonk** [comment]
P1_33 is labelled as as "1" under "PRU0" on the silkscreen. GPIO3.15 == GPIO111, so yes, it is GPIO111. Are you referencing something in the schematic? @derekmulcahy, which document is wrong??

**Comment by jadonk** [comment]
Ah, that diagram. Thanks!

**Comment by derekmulcahy** [comment]
Sorry, I didn't say it was on the Wiki FAQ page.

**Comment by jadonk** [comment]
Did I get it all? https://github.com/beagleboard/pocketbeagle/commit/cc3af73758f25dcc473f226d1892a21de610f96f

**Comment by derekmulcahy** [comment]
Yes, looks good.

**Comment by jadonk** [comment]
OK, I should have it updated on the wiki now too.
