### ISSUE TITLE
GPIO 44 labelled as 48 in silkscreen

### ISSUE THREAD

**Issue by brucepom** [beagleboard/pocketbeagle#13]
Thanks for an amazing board!

In my testing the pin labelled as 48 in the silkscreen is actually accessed as pin 44.

![image](https://user-images.githubusercontent.com/1694352/33344132-b1bd6d2e-d43c-11e7-9644-294b4bffbaa1.png)

I haven't found an official pinout illustration for PocketBeagle but I did find this one: http://files.linuxgizmos.com/bboard_pocketbeagle_pinout.jpg I'm unsure of the original source of this image but the image also describes that pin as 44.

**Comment by RobertCNelson** [comment]
@brucepom correct it's pin 44:

https://github.com/beagleboard/pocketbeagle/issues/4

https://github.com/beagleboard/pocketbeagle/wiki/FAQ#What_is_the_pinout_for_the_expansion_headers

Regards,

**Comment by mwelling** [comment]
This has already been corrected on the design files. Guessing that when the next production run commences they will update them. Might be a while though.

https://github.com/beagleboard/pocketbeagle/pull/8

**Comment by brucepom** [comment]
Thanks guys, looks like you were already on top of it. Really appreciate all your work. And thanks for the link to the pinout illustration, don't know how I missed that!
