### ISSUE TITLE
where's the PocketBeagle's linux kernel?

### ISSUE THREAD

**Issue by jackeyt** [beagleboard/pocketbeagle#17]
As you see,I had downloaded the PocketBeagle's image for my SD/TF card,and it runs also.
But I can't do more kernel platform development with the source  code  of PocketBeagle.
so , where's the source code of  PocketBeagle's linux kernel, please?

**Comment by dlech** [comment]
https://github.com/beagleboard/linux

**Comment by jackeyt** [comment]
I saw the version of  PocketBeagle's  is 'Linux version 4.9.82-ti-r102' by using command `cat proc/version` 
so , which branch is the right version for 4.9.82-ti-r102?

**Comment by dlech** [comment]
That is a "tag" rather than a "branch". You can find a list of tags at https://github.com/beagleboard/linux/tags.

**Comment by jackeyt** [comment]
Ohm,thanks!
I found it on web :[https://github.com/beagleboard/linux/releases/tag/4.9.82-ti-r102](url)
