### ISSUE TITLE
System Reference Manual pin 48 or 44? 

### ISSUE THREAD

**Issue by pakair** [beagleboard/pocketbeagle#22]
Fig. 41 shows the P2 header +3.3V as pin 48 but the next image Fig. 42 shows it as 44 (pin 24 of the P2)
which is it? thanks.

**Comment by fivdi** [comment]
See https://github.com/beagleboard/pocketbeagle/issues/13 and https://github.com/beagleboard/pocketbeagle/issues/4.

That being said, 3.3V is on P2_23 and not on P2_24.
