### ISSUE TITLE
Pocketbeagle not booting from SD card (but is visible on USB without the SDCARD)

### ISSUE THREAD

**Issue by nutilius** [beagleboard/pocketbeagle#25]
Hello everybody.
Yesterday I receiver PockedBeagle from Farnell and try to boot from SD card. Only Power LED is on, the rest is dead. I have tried 5 different cards with different size and 3 diffrent USB cables. 
System is dead. Whe system has card included, on attached linux system there is no USB device (no messages in dmesg also). I've tried two diffrent official Debian images from - current and last previous.
**When  I remove the card** and again attach board, I see new device  named Texas Instruments and dmesg also presents messages about new device.

**Comment by jadonk** [comment]
@nutilius The boot image is bad. The device has a USB boot mode in ROM, which is why you'd see it on your computer even without a valid boot image. You can possibly use BeagleBoot.

What steps are you following to program the microSD card?

**Comment by nutilius** [comment]
@jadonk Downloaded image was written to SD card by dd tool and later sync command was executed.

**Comment by nutilius** [comment]
Of course after decompressing using xz and veryfing checksum.

**Comment by nutilius** [comment]
The new part works good. Probably previous was damaged.
