### ISSUE TITLE
Graphics out

### ISSUE THREAD

**Issue by SinanAkkoyun** [beagleboard/pocketbeagle#32]
Hello!
I need to add an HDMI output to the pocketbeagle. (even if it requires a chip like the NXP TDA)

How can I go about that and how could I make it work with linux?
Thank you so much!

**Comment by mwelling** [comment]
Are you designing a new board based on the SiP or just trying to design an adapter for the PocketBeagle?

PocketBeagle does not break out all of the SiP's LCD display lines to headers you would need a display adapter from the available peripherals. USB might be able to do it but it won't be particularly performant.

If you are making a new board based on the SiP you can leverage the design from other Beagles (if you can source the chips):
![image](https://user-images.githubusercontent.com/1570196/203126266-7c9fc7b2-ba3b-44f7-a90c-60a6f5edf259.png)

**Comment by SinanAkkoyun** [comment]
I want to design a new board based on the SiP and reflow the chip from a pocket beagle

Thank you so much for the provided schematic!
