### ISSUE TITLE
GPIO44 is incorrectly labelled as GPIO48

### ISSUE THREAD

**Issue by jadonk** [beagleboard/pocketbeagle#4]

**Comment by mwelling** [comment]
@jadonk the latest pull request should fix the silkscreen issues on the Eagle and KiCAD designs.

Please confirm and merge or comment.

**Comment by jadonk** [comment]
I need to also update the revision to "A2a" where the small 'a' indicates a non-critical change that doesn't require any additional validation.

**Comment by mwelling** [comment]
@jadonk Okay. Can the Rev A2 be dropped from the KiCAD version altogether? With the latest commits the git revision is automatically stamped on the bottom silk when generating the gerbers.

**Comment by jadonk** [comment]
Added "A2a" designation in 9e4b05ea3dfb566ee7537ca8b0c1815f43e819ca
